export type Language = 'en' | 'hi' | 'ta';

export interface WeatherData {
  temp: number;
  humidity: number;
  description: string;
  city: string;
  forecast: { day: string; temp: number; condition: string }[];
}

export interface MarketPrice {
  crop: string;
  price: number;
  unit: string;
  trend: 'up' | 'down' | 'stable';
  image?: string;
}

export interface SoilData {
  ph: string;
  nitrogen: string;
  phosphorus: string;
  potassium: string;
  type: string;
  moisture: string;
}

export const TRANSLATIONS = {
  en: {
    title: "KrishiSathi",
    dashboard: "Dashboard",
    cropRec: "Crop Recommendation",
    weather: "Weather",
    soilHealth: "Soil Health",
    diseaseDet: "Disease Detection",
    marketPrices: "Market Prices",
    chatbot: "AI Chatbot",
    language: "Language",
    recommend: "Recommend",
    detect: "Detect",
    analyze: "Analyze",
    soilType: "Soil Type",
    ph: "pH Level",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    temp: "Temperature",
    humidity: "Humidity",
    rain: "Rain Prediction",
    alerts: "Alerts",
    yield: "Yield Prediction",
    price: "Price",
    trend: "Trend",
    unit: "Unit",
    login: "Login",
    logout: "Logout",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    welcomeBack: "Welcome Back",
    farmerLogin: "Farmer Login",
    irrigation: "Irrigation",
    monitoring: "Crop Monitoring",
    location: "Location",
    useGps: "Use GPS",
    manualLocation: "Manual Location",
    forecast: "Forecast",
    growthStage: "Growth Stage",
    healthStatus: "Health Status",
    waterNeeded: "Water Needed",
    irrigateNow: "Irrigate Now",
    monitoringResult: "Monitoring Result",
    moisture: "Soil Moisture",
    soilAnalysis: "Soil Health Analysis",
    fertilizerRec: "Fertilizer Recommendation",
    farmJournal: "Farm Journal",
    expenseTracker: "Expense Tracker",
    inventory: "Inventory",
    addActivity: "Add Activity",
    addExpense: "Add Expense",
    addStock: "Add Stock",
    income: "Income",
    expense: "Expense",
    profit: "Profit",
    stockLevel: "Stock Level",
    cropName: "Crop Name",
    year: "Year",
    date: "Date",
    search: "Search",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    dangerAlert: "Danger Alert",
    cropDanger: "Your crop is at risk! High probability of pest attack detected.",
    weatherAlert: "Extreme weather warning: Heavy rainfall expected in 24 hours.",
    journalInfo: "The Farm Journal helps you keep a daily record of all farming activities, from sowing to harvest. It's essential for tracking progress, identifying patterns, and improving future yields.",
    whatIsJournal: "What is Farm Journal?",
    editProfile: "Edit Profile",
    saveProfile: "Save Profile",
    farmerName: "Farmer Name",
    farmerId: "Farmer ID",
    avatarSeed: "Avatar Style",
    totalExpenses: "Total Expenses",
    totalIncome: "Total Income",
    inventoryItems: "Inventory Items",
    journalEntries: "Journal Entries",
    checkRainProb: "Check Rain Probability",
    rainProb: "Rain Probability",
    analyzing: "Analyzing...",
  },
  hi: {
    title: "कृषिसार्थी",
    dashboard: "डैशबोर्ड",
    cropRec: "फसल सिफारिश",
    weather: "मौसम",
    soilHealth: "मिट्टी का स्वास्थ्य",
    diseaseDet: "रोग का पता लगाना",
    marketPrices: "बाजार भाव",
    chatbot: "AI चैटबॉट",
    language: "भाषा",
    recommend: "सिफारिश करें",
    detect: "पता लगाएं",
    analyze: "विश्लेषण करें",
    soilType: "मिट्टी का प्रकार",
    ph: "pH स्तर",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassium: "पोटेशियम (K)",
    temp: "तापमान",
    humidity: "नमी",
    rain: "बारिश की भविष्यवाणी",
    alerts: "अलर्ट",
    yield: "पैदावार की भविष्यवाणी",
    price: "कीमत",
    trend: "रुझान",
    unit: "इकाई",
    login: "लॉगिन",
    logout: "लॉगआउट",
    email: "ईमेल",
    password: "पासवर्ड",
    signIn: "साइन इन करें",
    welcomeBack: "वापसी पर स्वागत है",
    farmerLogin: "किसान लॉगिन",
    irrigation: "सिंचाई",
    monitoring: "फसल निगरानी",
    location: "स्थान",
    useGps: "GPS का उपयोग करें",
    manualLocation: "मैन्युअल स्थान",
    forecast: "पूर्वानुमान",
    growthStage: "विकास चरण",
    healthStatus: "स्वास्थ्य स्थिति",
    waterNeeded: "पानी की आवश्यकता",
    irrigateNow: "अभी सिंचाई करें",
    monitoringResult: "निगरानी परिणाम",
    moisture: "मिट्टी की नमी",
    soilAnalysis: "मिट्टी स्वास्थ्य विश्लेषण",
    fertilizerRec: "उर्वरक सिफारिश",
    farmJournal: "फार्म जर्नल",
    expenseTracker: "व्यय ट्रैकर",
    inventory: "इन्वेंटरी",
    addActivity: "गतिविधि जोड़ें",
    addExpense: "खर्च जोड़ें",
    addStock: "स्टॉक जोड़ें",
    income: "आय",
    expense: "खर्च",
    profit: "लाभ",
    stockLevel: "स्टॉक स्तर",
    cropName: "फसल का नाम",
    year: "वर्ष",
    date: "तारीख",
    search: "खोजें",
    notifications: "सूचनाएं",
    noNotifications: "कोई नई सूचना नहीं",
    dangerAlert: "खतरे की चेतावनी",
    cropDanger: "आपकी फसल खतरे में है! कीट हमले की उच्च संभावना का पता चला है।",
    weatherAlert: "अत्यधिक मौसम की चेतावनी: 24 घंटों में भारी बारिश की उम्मीद है।",
    journalInfo: "फार्म जर्नल आपको बुवाई से लेकर कटाई तक की सभी कृषि गतिविधियों का दैनिक रिकॉर्ड रखने में मदद करता है। यह प्रगति पर नज़र रखने, पैटर्न की पहचान करने और भविष्य की पैदावार में सुधार के लिए आवश्यक है।",
    whatIsJournal: "फार्म जर्नल क्या है?",
    editProfile: "प्रोफ़ाइल संपादित करें",
    saveProfile: "प्रोफ़ाइल सहेजें",
    farmerName: "किसान का नाम",
    farmerId: "किसान आईडी",
    avatarSeed: "अवतार शैली",
    totalExpenses: "कुल व्यय",
    totalIncome: "कुल आय",
    inventoryItems: "इन्वेंटरी आइटम",
    journalEntries: "जर्नल प्रविष्टियां",
    checkRainProb: "बारिश की संभावना जांचें",
    rainProb: "बारिश की संभावना",
    analyzing: "विश्लेषण कर रहा है...",
  },
  ta: {
    title: "கிருஷிசாதி",
    dashboard: "டாஷ்போர்டு",
    cropRec: "பயிர் பரிந்துரை",
    weather: "வானிலை",
    soilHealth: "மண் ஆரோக்கியம்",
    diseaseDet: "நோய் கண்டறிதல்",
    marketPrices: "சந்தை விலைகள்",
    chatbot: "AI சாட்போட்",
    language: "மொழி",
    recommend: "பரிந்துரை",
    detect: "கண்டறி",
    analyze: "ஆராய்",
    soilType: "மண் வகை",
    ph: "pH அளவு",
    nitrogen: "நைட்ரஜன் (N)",
    phosphorus: "பாஸ்பரஸ் (P)",
    potassium: "பொட்டாசியம் (K)",
    temp: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    rain: "மழை கணிப்பு",
    alerts: "எச்சரிக்கைகள்",
    yield: "விளைச்சல் கணிப்பு",
    price: "விலை",
    trend: "போக்கு",
    unit: "அலகு",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signIn: "உள்நுழைக",
    welcomeBack: "மீண்டும் வருக",
    farmerLogin: "விவசாயி உள்நுழைவு",
    irrigation: "நீர்ப்பாசனம்",
    monitoring: "பயிர் கண்காணிப்பு",
    location: "இடம்",
    useGps: "GPS பயன்படுத்தவும்",
    manualLocation: "கைமுறை இடம்",
    forecast: "முன்னறிவிப்பு",
    growthStage: "வளர்ச்சி நிலை",
    healthStatus: "ஆரோக்கிய நிலை",
    waterNeeded: "தேவையான தண்ணீர்",
    irrigateNow: "இப்போது நீர்ப்பாசனம் செய்யுங்கள்",
    monitoringResult: "கண்காணிப்பு முடிவு",
    moisture: "மண் ஈரப்பதம்",
    soilAnalysis: "மண் ஆரோக்கிய பகுப்பாய்வு",
    fertilizerRec: "உர பரிந்துரை",
    farmJournal: "பண்ணை இதழ்",
    expenseTracker: "செலவு கண்காணிப்பு",
    inventory: "சரக்கு",
    addActivity: "செயல்பாட்டைச் சேர்",
    addExpense: "செலவைச் சேர்",
    addStock: "பங்குகளைச் சேர்",
    income: "வருமானம்",
    expense: "செலவு",
    profit: "லாபம்",
    stockLevel: "பங்கு நிலை",
    cropName: "பயிர் பெயர்",
    year: "ஆண்டு",
    date: "தேதி",
    search: "தேடல்",
    notifications: "அறிவிப்புகள்",
    noNotifications: "புதிய அறிவிப்புகள் இல்லை",
    dangerAlert: "ஆபத்து எச்சரிக்கை",
    cropDanger: "உங்கள் பயிர் ஆபத்தில் உள்ளது! பூச்சி தாக்குதல் கண்டறியப்பட்டுள்ளது.",
    weatherAlert: "தீவிர வானிலை எச்சரிக்கை: 24 மணிநேரத்தில் பலத்த மழை எதிர்பார்க்கப்படுகிறது.",
    journalInfo: "பண்ணை இதழ் விதைப்பு முதல் அறுவடை வரை அனைத்து விவசாய நடவடிக்கைகளின் தினசரி பதிவை வைத்திருக்க உதவுகிறது. முன்னேற்றத்தைக் கண்காணிப்பதற்கும், வடிவங்களை அடையாளம் காண்பதற்கும், எதிர்கால விளைச்சலை மேம்படுத்துவதற்கும் இது அவசியம்.",
    whatIsJournal: "பண்ணை இதழ் என்றால் என்ன?",
    editProfile: "சுயவிவரத்தைத் திருத்து",
    saveProfile: "சுயவிவரத்தைச் சேமி",
    farmerName: "விவசாயி பெயர்",
    farmerId: "விவசாயி ஐடி",
    avatarSeed: "அவதார் பாணி",
    totalExpenses: "மொத்த செலவுகள்",
    totalIncome: "மொத்த வருமானம்",
    inventoryItems: "சரக்கு பொருட்கள்",
    journalEntries: "ஜர்னல் பதிவுகள்",
    checkRainProb: "மழை பெய்யும் வாய்ப்பைச் சரிபார்க்கவும்",
    rainProb: "மழை பெய்யும் வாய்ப்பு",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
  },
};
